/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState, useEffect, useRef } from 'react';
import { AIJob, ActivityLog } from '../types';
import { 
  Play, 
  Terminal, 
  Trash2, 
  CheckCircle2, 
  XCircle,
  Activity, 
  ShieldAlert, 
  DollarSign, 
  ArrowUpRight,
  TrendingUp,
  RotateCcw
} from 'lucide-react';

interface SimulationSandboxProps {
  activeJobs: AIJob[];
  initialJobId?: string;
}

export const SimulationSandbox: React.FC<SimulationSandboxProps> = ({ activeJobs, initialJobId }) => {
  const [selectedJobId, setSelectedJobId] = useState<string>(initialJobId || '');
  const [isRunning, setIsRunning] = useState<boolean>(false);
  const [logs, setLogs] = useState<ActivityLog[]>([]);
  const [metricImpact, setMetricImpact] = useState<number>(0);
  const [dispatchedBudget, setDispatchedBudget] = useState<number>(0);
  const [humanDecisionRequest, setHumanDecisionRequest] = useState<{
    id: string;
    message: string;
    details: string;
  } | null>(null);

  const logsEndRef = useRef<HTMLDivElement>(null);
  const selectedJob = activeJobs.find(j => j.id === selectedJobId);

  // Auto-scroll logs
  useEffect(() => {
    if (logsEndRef.current) {
      logsEndRef.current.scrollIntoView({ behavior: 'smooth' });
    }
  }, [logs]);

  // Handle simulation log ticks when running
  useEffect(() => {
    if (!isRunning || !selectedJob) return;

    let intervalId: NodeJS.Timeout;
    let logCounter = 0;

    const logTemplates = [
      () => ({
        message: `Querying localized demographic feed for zipcode area targets...`,
        status: 'info' as const,
        triggerDecision: false
      }),
      () => ({
        message: `Connected through securely tunneled API to state geographic coordination registry. Flagging critical hotspots.`,
        status: 'info' as const,
        triggerDecision: false
      }),
      () => ({
        message: `Telemetry warning loaded: Urgent demand spike matching ${selectedJob.aiSubsystemName} threshold.`,
        status: 'warning' as const,
        triggerDecision: false
      }),
      () => ({
        message: `Triggering immediate dispatch proposal. Associated Budget Source: ${selectedJob.federalAgencyCollaborator}.`,
        status: 'info' as const,
        triggerDecision: false
      }),
      () => ({
        message: `PILOT GATE: Triggering Dynamic Student Audit. Awaiting Human-in-the-Loop qualitative confirmation before funding dispatch.`,
        status: 'critical' as const,
        triggerDecision: true
      })
    ];

    const generateLog = () => {
      if (logCounter >= logTemplates.length) {
        // Recycle log messages to keep playground active
        logCounter = 0;
      }

      const template = logTemplates[logCounter];
      const logDetails = template();

      const newLog: ActivityLog = {
        id: `log-${Date.now()}`,
        timestamp: new Date().toLocaleTimeString(),
        jobId: selectedJob.id,
        jobTitle: selectedJob.title,
        message: logDetails.message,
        status: logDetails.status
      };

      setLogs(prev => [...prev, newLog]);

      if (logDetails.triggerDecision) {
        setIsRunning(false); // Pause simulation to wait for human veto/approval
        setHumanDecisionRequest({
          id: `dec-${Date.now()}`,
          message: `${selectedJob.aiHumanLoopTask}`,
          details: `Recommendation generated by: ${selectedJob.aiSubsystemName}. Source Funding requested: $${selectedJob.fundingAllocationSimulated.toLocaleString()} USD from collaborative ledger.`
        });
      }

      logCounter++;
    };

    // Spawn first immediate log
    generateLog();
    
    intervalId = setInterval(() => {
      generateLog();
    }, 4500);

    return () => clearInterval(intervalId);
  }, [isRunning, selectedJobId]);

  const handleStartSimulation = (jobId: string) => {
    if (!jobId) return;
    setSelectedJobId(jobId);
    setIsRunning(true);
    setHumanDecisionRequest(null);
    const bootLog: ActivityLog = {
      id: `boot-${Date.now()}`,
      timestamp: new Date().toLocaleTimeString(),
      jobId: jobId,
      jobTitle: activeJobs.find(j => j.id === jobId)?.title || '',
      message: `System Initializing. Booting associated AI coordination subsystems...`,
      status: 'success'
    };
    setLogs([bootLog]);
    setMetricImpact(0);
    setDispatchedBudget(0);
  };

  useEffect(() => {
    if (initialJobId) {
      handleStartSimulation(initialJobId);
    }
  }, [initialJobId]);

  const handleDecisionConfirm = (approved: boolean) => {
    if (!selectedJob || !humanDecisionRequest) return;

    const auditMessage = approved 
      ? `Audit Confirmed by Student: Action approved. Generating immutable ledger entry. Disbursing public seed resources.`
      : `Audit Vetoed by Student: Action aborted. Overriding neural recommendation. Flagging scenario for team retraining.`;

    const resultLog: ActivityLog = {
      id: `res-${Date.now()}`,
      timestamp: new Date().toLocaleTimeString(),
      jobId: selectedJob.id,
      jobTitle: selectedJob.title,
      message: auditMessage,
      status: approved ? 'success' : 'warning'
    };

    setLogs(prev => [...prev, resultLog]);
    setHumanDecisionRequest(null);

    if (approved) {
      setMetricImpact(prev => Math.min(100, prev + 18));
      setDispatchedBudget(prev => prev + selectedJob.fundingAllocationSimulated);
      
      // Resume simulation loop with success milestones
      setTimeout(() => {
        setLogs(prev => [...prev, {
          id: `success-${Date.now()}`,
          timestamp: new Date().toLocaleTimeString(),
          jobId: selectedJob.id,
          jobTitle: selectedJob.title,
          message: `Success: Sourced telemetry confirms 100% matching efficacy. Direct benefit allocated to neighborhood target clusters.`,
          status: 'success'
        }]);
      }, 1500);
    } else {
      setTimeout(() => {
        setLogs(prev => [...prev, {
          id: `aborted-${Date.now()}`,
          timestamp: new Date().toLocaleTimeString(),
          jobId: selectedJob.id,
          jobTitle: selectedJob.title,
          message: `Safe State Reestablished. Awaiting user telemetry inputs to formulate next dispatch matrix.`,
          status: 'info'
        }]);
      }, 1500);
    }
    
    // Resume simulation running state
    setIsRunning(true);
  };

  const handleClearTerminal = () => {
    setLogs([]);
    setIsRunning(false);
    setHumanDecisionRequest(null);
    setMetricImpact(0);
    setDispatchedBudget(0);
  };

  return (
    <div id="simulation-sandbox-section" className="bg-slate-900/60 border border-slate-800 rounded-2xl p-6">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-6 pb-6 border-b border-slate-800/80">
        <div>
          <div className="flex items-center gap-2 mb-1.5">
            <Terminal className="w-5 h-5 text-emerald-400" />
            <span className="text-xs font-mono uppercase tracking-wider text-emerald-400 font-bold">Execution Simulator</span>
          </div>
          <h2 className="text-lg font-bold text-slate-100 font-sans tracking-tight">
            Municipal AI-Job De-escalation Sandbox
          </h2>
          <p className="text-xs text-slate-400 max-w-xl">
            Test and simulate the daily flow of any created AI public-benefits career in real-world scenarios. Monitor live telemetry feedback and audit critical systemic recommendations before budgets disburse.
          </p>
        </div>

        {/* Action Select Box */}
        <div className="flex flex-wrap items-center gap-2 shrink-0">
          <select
            id="sim-job-select"
            value={selectedJobId}
            onChange={(e) => handleStartSimulation(e.target.value)}
            className="bg-slate-950 border border-slate-800 text-xs text-slate-200 rounded-lg px-3 py-2 font-mono"
          >
            <option value="">-- Choose AI Position --</option>
            {activeJobs.map((j) => (
              <option key={j.id} value={j.id}>
                {j.title} [{j.id.split('-').pop()}]
              </option>
            ))}
          </select>

          {selectedJobId && (
            <button
              onClick={() => handleStartSimulation(selectedJobId)}
              className="p-2 bg-emerald-500/10 border border-emerald-500/20 hover:bg-emerald-500/20 text-emerald-400 rounded-lg transition-all duration-200"
              title="Restart Simulation"
            >
              <RotateCcw className="w-4 h-4" />
            </button>
          )}
        </div>
      </div>

      {selectedJob ? (
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-stretch">
          {/* Main Visual Terminal log */}
          <div className="lg:col-span-8 flex flex-col bg-slate-950 border border-slate-800/80 rounded-xl relative overflow-hidden h-[380px]">
            {/* Terminal Header bar */}
            <div className="bg-slate-900/80 px-4 py-2 flex items-center justify-between border-b border-slate-950">
              <div className="flex items-center gap-2">
                <span className="w-2.5 h-2.5 rounded-full bg-rose-500"></span>
                <span className="w-2.5 h-2.5 rounded-full bg-amber-500"></span>
                <span className="w-2.5 h-2.5 rounded-full bg-emerald-500"></span>
                <span className="text-[10px] font-mono font-semibold text-slate-400 tracking-wider ml-2 truncate">
                  {selectedJob.aiSubsystemName} // shell_v2.0
                </span>
              </div>

              <div className="flex items-center gap-2">
                <span className={`inline-flex items-center gap-1 text-[9px] font-mono px-2 py-0.5 rounded leading-none ${
                  isRunning 
                    ? 'bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 animate-pulse'
                    : 'bg-amber-500/10 text-amber-400 border border-amber-500/20'
                }`}>
                  <Activity className="w-2.5 h-2.5 shrink-0" />
                  {isRunning ? 'LIVE FEED' : 'WAITING DECISION'}
                </span>

                <button
                  onClick={handleClearTerminal}
                  className="p-1 hover:bg-slate-800 text-slate-500 hover:text-rose-400 rounded transition-colors duration-200"
                  title="Clear Terminal logs"
                >
                  <Trash2 className="w-3.5 h-3.5" />
                </button>
              </div>
            </div>

            {/* Terminal Logs area */}
            <div className="flex-1 overflow-y-auto p-4 font-mono text-xs text-left space-y-2.5">
              {logs.map((log) => (
                <div key={log.id} className="flex items-start gap-2 leading-relaxed">
                  <span className="text-slate-500 shrink-0 select-none text-[10px]">{log.timestamp}</span>
                  <span className={`font-semibold shrink-0 uppercase text-[9px] px-1 rounded ${
                    log.status === 'success' ? 'bg-emerald-500/10 text-emerald-400 border border-emerald-500/10' :
                    log.status === 'warning' ? 'bg-amber-500/10 text-amber-400 border border-amber-500/10' :
                    log.status === 'critical' ? 'bg-rose-500/10 text-rose-400 border border-rose-500/10' :
                    'bg-sky-500/10 text-sky-400 border border-sky-500/10'
                  }`}>
                    {log.status}
                  </span>
                  <span className={`${
                    log.status === 'success' ? 'text-emerald-300' :
                    log.status === 'warning' ? 'text-amber-300' :
                    log.status === 'critical' ? 'text-rose-300' :
                    'text-slate-300'
                  }`}>
                    {log.message}
                  </span>
                </div>
              ))}

              <div ref={logsEndRef} />
            </div>

            {/* Human Decision Gateway modal-style overlay anchor inside terminal */}
            {humanDecisionRequest && (
              <div className="absolute inset-x-0 bottom-0 bg-slate-900 border-t border-rose-500/30 p-5 text-left flex flex-col gap-3">
                <div className="flex items-center gap-2">
                  <ShieldAlert className="w-4 h-4 text-rose-400 shrink-0" />
                  <h4 className="text-xs font-mono uppercase font-bold text-rose-400 tracking-wider">
                    HUMAN-IN-THE-LOOP AUDIT REQUIREMENT
                  </h4>
                </div>
                <div>
                  <p className="text-xs text-slate-200 font-sans leading-relaxed">
                    <span className="font-semibold font-mono text-amber-400">Task Audit Prompt:</span> {humanDecisionRequest.message}
                  </p>
                  <p className="text-[10px] text-slate-400 leading-normal mt-1.5 font-sans italic">
                    {humanDecisionRequest.details}
                  </p>
                </div>
                <div className="flex gap-2.5 justify-end mt-1 font-mono">
                  <button
                    onClick={() => handleDecisionConfirm(false)}
                    className="flex items-center gap-1.5 px-3 py-1.5 bg-rose-500/10 hover:bg-rose-500/20 border border-rose-500/20 text-rose-400 text-xs rounded transition-all duration-200"
                  >
                    <XCircle className="w-4 h-4 text-rose-400" />
                    VETO DECISION
                  </button>
                  <button
                    onClick={() => handleDecisionConfirm(true)}
                    className="flex items-center gap-1.5 px-4 py-1.5 bg-emerald-500 hover:bg-emerald-400 text-slate-950 font-bold text-xs rounded transition-all duration-200"
                  >
                    <CheckCircle2 className="w-4 h-4 text-slate-950" />
                    APPROVE DISPATCH
                  </button>
                </div>
              </div>
            )}
          </div>

          {/* KPI and Dashboard indicators */}
          <div className="lg:col-span-4 flex flex-col gap-4">
            {/* Simulated Live Stats Grid */}
            <div className="bg-slate-950/40 border border-slate-800/60 rounded-xl p-4 text-left">
              <h3 className="text-[10px] font-mono uppercase text-slate-400 tracking-wider mb-3">Live Session Metrics</h3>

              <div className="space-y-4">
                {/* Metr 1: Targeted Community Benefit */}
                <div>
                  <div className="flex justify-between text-xs text-slate-400 font-mono mb-1">
                    <span>Efficacy Progress</span>
                    <span className="font-bold text-slate-200">{metricImpact}%</span>
                  </div>
                  <div className="w-full bg-slate-900 border border-slate-850 h-2 rounded-full overflow-hidden">
                    <div 
                      className="bg-emerald-500 h-full transition-all duration-500"
                      style={{ width: `${metricImpact}%` }}
                    ></div>
                  </div>
                </div>

                {/* Metr 2: Dispatched Pilot Budget */}
                <div>
                  <div className="flex justify-between text-xs text-slate-400 font-mono mb-1">
                    <span>Disbursed Pilot Budget</span>
                    <span className="font-bold text-slate-200">${dispatchedBudget.toLocaleString()}</span>
                  </div>
                  <div className="p-3 bg-slate-900 border border-slate-850 rounded-lg flex items-center justify-between">
                    <span className="text-[10px] font-mono text-slate-500 uppercase">Total Grant Locked</span>
                    <span className="text-xs font-mono font-semibold text-sky-400 flex items-center gap-0.5">
                      <DollarSign className="w-3.5 h-3.5 text-sky-400" />
                      {(selectedJob.fundingAllocationSimulated).toLocaleString()}
                    </span>
                  </div>
                </div>
              </div>
            </div>

            {/* Selected job profile briefing panel */}
            <div className="bg-slate-950/40 border border-slate-800/60 rounded-xl p-4 text-left flex-1 flex flex-col justify-between">
              <div>
                <h4 className="text-[10px] uppercase font-mono tracking-wider text-slate-400 mb-2">Simulated Career Role</h4>
                <h4 className="text-sm font-semibold text-slate-200 tracking-tight leading-snug">
                  {selectedJob.title}
                </h4>
                <p className="text-xs text-slate-400 mt-2 leading-relaxed">
                  {selectedJob.roleSummary}
                </p>
              </div>

              {/* Targets indices */}
              <div className="pt-4 border-t border-slate-800/60 mt-4">
                <p className="text-[10px] font-mono tracking-wider text-slate-500 uppercase mb-2">Target Impact Metrics:</p>
                <div className="space-y-1 text-[11px] text-slate-300">
                  {selectedJob.societalImpactTargets.map((t, idx) => (
                    <div key={idx} className="flex items-start gap-1.5 leading-snug">
                      <TrendingUp className="w-3.5 h-3.5 text-emerald-400 shrink-0 mt-0.5" />
                      <span>{t}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </div>
      ) : (
        <div className="border border-dashed border-slate-800 bg-slate-950/20 text-center py-12 rounded-xl">
          <Terminal className="w-8 h-8 text-slate-700 mx-auto mb-3" />
          <p className="text-sm text-slate-400">No active simulation loaded.</p>
          <p className="text-xs text-slate-500 mt-1 max-w-sm mx-auto leading-relaxed">
            Select an active university AI position from the top dropdown or create a new student role in the Workshop to begin field simulation testing.
          </p>
        </div>
      )}
    </div>
  );
};
